ok,error
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
False,"/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/huzaifaiftikhar/premkt-algo/backtest.py': [Errno 2] No such file or directory
"
